name: Build app & upload to AppCenter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - test1
      - test2
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print result 
      run: ls
