name: Build app & upload to AppCenter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - test1
      - test2
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: E2E Test
    #   run: |
    #     export RELEASE_NUMBER=123
    #     curl -X POST https://api.github.com/repos/Fouz/Trivia-Api/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u 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 --data '{"event_type": "e2e", "client_payload": { "repo": "'"$GITHUB_REPOSITORY"'","PR": "'"${{ github.event.number }}"'","number": "'"$RELEASE_NUMBER"'"}}'

    - name: Test app
      continue-on-error: true
      # continue-on-error: ${{  github.event_name == 'repository_dispatch'  }}
      id: test-app 
      run: |
        # echo "Testing app (randomly fails)"
        # if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
        echo "this is an error message!"
        exit 1
    - name: print result 
      run: |
        echo "${{steps.response.outputs.result}}"
