name: Build app & upload to AppCenter

on:
  pull_request:
    branches:
      - master
      - test1
      - test2
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: E2E Test
      run: |
        export RELEASE_NUMBER=123
        curl -X POST https://api.github.com/repos/Fouz/Trivia-Api/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u 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 --data '{"event_type": "e2e", "client_payload": {}}'