name: Build app & upload to AppCenter

on:
  pull_request:
    branches:
      - master
      - test2
      types: [opened, reopened, synchronize]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: E2E Test
      run: |
        curl -X POST https://api.github.com/repos/Fouz/Trivia-Api/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u 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 \
        --data '{"event_type": "e2e", "client_payload": { "repo": "'"$GITHUB_REPOSITORY"'","PR": "'"${{ github.event.number }}"'" }}'
              